### PR TITLE
remove getsource command

### PR DESCRIPTION
**Pull request by aeeilllmrx**
Previously getsource got stuck in an endless loop. Now (I assume, see image below) it does the correct thing.

Screenshot 2024-11-25 at 11 03 36 AM

### CODE REVIEW

**Comment by TheOriginalSoni** [comment]
It does not do the correct thing still.

Ideally it would type "more code" with backticks as well. Just escaped out using \ instead.

**Comment by aeeilllmrx** [comment]
New result:
Screenshot 2024-11-25 at 12 01 09 PM

**Comment by aeeilllmrx** [comment]
This is deprecated now since Discord natively implements this with "copy text"

**Comment by aeeilllmrx** [comment]
New change implemented in https://github.com/PuzzleTechHub/bot-be-named/pull/201/files

**Pull request closed without merging**
